FROM quay.io/centos/centos:stream9

LABEL maintainer="Sebastian Scheinkman <sebassch@gmail.com>"

ARG DPDK_VER=24.11.4
ENV DPDK_VER=${DPDK_VER}
ENV DPDK_DIR=/usr/src/dpdk-stable-${DPDK_VER}
ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig

RUN dnf install -y dnf-plugins-core \
    && dnf config-manager --set-enabled crb \
    && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && dnf install -y \
        diffutils \
        ethtool \
        expect \
        gcc \
        gcc-c++ \
        git \
        htop \
        iproute \
        libibverbs \
        libibverbs-devel \
        logrotate \
        lua \
        make \
        meson \
        net-tools \
        ninja-build \
        numactl \
        numactl-devel \
        patch \
        perf \
        pkgconf-pkg-config \
        python3 \
        python3-pip \
        readline-devel \
        sysstat \
        tcpdump \
        wget \
        which \
        xz \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN pip3 install --no-cache-dir pyelftools

RUN cd /usr/src \
    && wget https://fast.dpdk.org/rel/dpdk-${DPDK_VER}.tar.xz \
    && tar -xpf dpdk-${DPDK_VER}.tar.xz \
    && rm dpdk-${DPDK_VER}.tar.xz \
    && cd ${DPDK_DIR} \
    && meson setup build -Denable_docs=false -Dbuildtype=release \
    && meson compile -C build \
    && meson install -C build \
    && printf "/usr/local/lib64\n/usr/local/lib\n" > /etc/ld.so.conf.d/dpdk.conf \
    && ldconfig

COPY scripts/* /usr/bin/

WORKDIR ${DPDK_DIR}
