FROM quay.io/centos/centos:stream9

ARG DPDK_VER=24.11.4
ARG PKTGEN_VER=26.03.0

ENV DPDK_VER=${DPDK_VER}
ENV PKTGEN_VER=${PKTGEN_VER}
ENV DPDK_DIR=/usr/src/dpdk-stable-${DPDK_VER}
ENV PKTGEN_DIR=/opt/pktgen-dpdk
ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig

RUN dnf install -y dnf-plugins-core \
    && dnf config-manager --set-enabled crb \
    && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && dnf install -y \
        diffutils \
        ethtool \
        gcc \
        gcc-c++ \
        git \
        htop \
        hostname \
        iproute \
        iputils \
        libbsd-devel \
        libibverbs \
        libibverbs-devel \
        libpcap-devel \
        lua-devel \
        make \
        meson \
        ncurses-devel \
        net-tools \
        ninja-build \
        numactl \
        numactl-devel \
        patch \
        perf \
        pkgconf-pkg-config \
        procps-ng \
        python3 \
        python3-pip \
        rdma-core-devel \
        sysstat \
        tcpdump \
        vim \
        wget \
        which \
        xz \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN pip3 install --no-cache-dir pyelftools

RUN cd /usr/src \
    && wget https://fast.dpdk.org/rel/dpdk-${DPDK_VER}.tar.xz \
    && tar -xpf dpdk-${DPDK_VER}.tar.xz \
    && rm dpdk-${DPDK_VER}.tar.xz \
    && cd ${DPDK_DIR} \
    && meson setup build -Denable_docs=false -Dbuildtype=release \
    && meson compile -C build \
    && meson install -C build \
    && printf "/usr/local/lib64\n/usr/local/lib\n" > /etc/ld.so.conf.d/dpdk.conf \
    && ldconfig

RUN cd /opt \
    && wget https://github.com/Pktgen/Pktgen-DPDK/archive/refs/tags/pktgen-${PKTGEN_VER}.tar.gz -O pktgen-${PKTGEN_VER}.tar.gz \
    && tar -xpf pktgen-${PKTGEN_VER}.tar.gz \
    && rm pktgen-${PKTGEN_VER}.tar.gz \
    && mv Pktgen-DPDK-pktgen-${PKTGEN_VER} ${PKTGEN_DIR} \
    && cd ${PKTGEN_DIR} \
    && meson setup builddir \
    && meson compile -C builddir \
    && ln -sf ${PKTGEN_DIR}/builddir/app/pktgen /usr/local/bin/pktgen

WORKDIR ${PKTGEN_DIR}
