FROM registry.redhat.io/openshift4/dpdk-base-rhel8:latest

LABEL maintainer="Sebastian Scheinkman <sebassch@gmail.com>"

USER 0

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && dnf clean all

COPY repo/* /etc/yum.repos.d/

RUN dnf install -y perf htop net-tools tcpdump && dnf clean all

COPY scripts/* /usr/bin/
