FROM quay.io/centos/centos:stream9

RUN dnf install -y dnf-plugins-core \
    && dnf config-manager --set-enabled crb \
    && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && dnf install -y --nodocs \
        bind-utils \
        bpftrace \
        catatonit \
        htop \
        iperf3 \
        iproute \
        iputils \
        libcap \
        net-tools \
        perf \
        procps-ng \
        strace \
        tcpdump \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN setcap CAP_NET_ADMIN,CAP_NET_RAW=+ep /usr/sbin/ip \
    && setcap CAP_NET_ADMIN=+ep /usr/sbin/route

ENTRYPOINT [ "/usr/libexec/catatonit/catatonit", "--" ]
CMD ["/bin/bash", "-c", "sleep INF"]
