FROM quay.io/centos/centos:8

# install requirements
RUN dnf install dnf-plugins-core -y && dnf config-manager --set-enabled powertools && dnf -y install --nodocs git wget procps python3 vim python3-pip pciutils gettext https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && dnf clean all
RUN dnf install -y --nodocs hostname iproute net-tools ethtool nmap iputils perf numactl sysstat htop rdma-core-devel libibverbs libibverbs-devel net-tools tcpdump && dnf clean all

COPY repo/vpp.repo /etc/yum.repos.d/vpp.repo
RUN dnf install -y vpp vpp-plugins vpp-devel

WORKDIR /opt/
COPY scripts /opt/scripts
