---
- name: Install and Configure GitHub Actions Runners
  hosts: hypervisors
  become: yes
  gather_facts: yes

  vars:
    runner_version: "2.330.0"
    runner_user: "github-runner"
    runner_base_dir: "/home/{{ runner_user }}/runners"
    runner_archive: "actions-runner-linux-x64-{{ runner_version }}.tar.gz"
    runner_download_url: "https://github.com/actions/runner/releases/download/v{{ runner_version }}/{{ runner_archive }}"
    
    # Configuration should be loaded from group_vars or passed as extra-vars
    # Example: ansible-playbook install-gh-runners.yaml -e @secrets.yml
    configurations: "{{ runner_configurations | default([]) }}"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - runner_user is defined
          - configurations is defined
          - configurations | length > 0
          - runner_tokens is defined
        fail_msg: "Required variables are missing. Please provide runner_configurations and runner_tokens."

    - name: Check that runner_tokens are provided securely
      assert:
        that:
          - runner_tokens is defined
          - runner_tokens is mapping
        fail_msg: "runner_tokens must be provided via ansible-vault or extra-vars, not in group_vars"

    - name: Verify SSH key exists for runner user
      stat:
        path: "/home/{{ runner_user }}/.ssh/id_rsa"
      register: runner_ssh_key_check

    - name: Fail if SSH key is missing
      fail:
        msg: "SSH key is required for kcli. Run 'ansible-playbook prepare-server.yaml' first to create it."
      when: not runner_ssh_key_check.stat.exists

  tasks:
    - name: Ensure runner user exists
      user:
        name: "{{ runner_user }}"
        comment: "GitHub Actions Runner"
        system: yes
        shell: /bin/bash
        create_home: yes
        home: "/home/{{ runner_user }}"
      tags: ['setup', 'users']

    - name: Add runner user to libvirt group
      user:
        name: "{{ runner_user }}"
        groups: libvirt
        append: yes
      tags: ['setup', 'users']

    - name: Create runner base directory
      file:
        path: "{{ runner_base_dir }}"
        state: directory
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
        mode: '0755'
      tags: ['setup']

    - name: Download GitHub Actions runner archive
      get_url:
        url: "{{ runner_download_url }}"
        dest: "/tmp/{{ runner_archive }}"
        mode: '0644'
        timeout: 300
      retries: 3
      delay: 10
      register: runner_download
      until: runner_download is succeeded
      tags: ['download']

    - name: Create individual runner directories
      file:
        path: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}"
        state: directory
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
        mode: '0755'
      loop: "{{ configurations }}"
      tags: ['setup']

    - name: Extract runner to individual directories
      unarchive:
        src: "/tmp/{{ runner_archive }}"
        dest: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}/"
        remote_src: yes
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
      loop: "{{ configurations }}"
      tags: ['install']

    - name: Template environment configuration for each runner
      template:
        src: files/env-template.j2
        dest: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}/.env"
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
        mode: '0644'
      loop: "{{ configurations }}"
      register: env_file_updated
      no_log: true  # Don't log environment variables
      tags: ['config']

    - name: Update runner .path file with correct PATH for all tools
      copy:
        dest: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}/.path"
        content: "/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
        mode: '0644'
      loop: "{{ configurations }}"
      register: path_file_updated
      tags: ['config']

    - name: Create .kcli directory for runner user
      file:
        path: "/home/{{ runner_user }}/.kcli"
        state: directory
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
        mode: '0755'
      tags: ['config']

    - name: Create kcli config with explicit SSH key
      copy:
        dest: "/home/{{ runner_user }}/.kcli/config.yml"
        content: |
          default:
            keypair: /home/{{ runner_user }}/.ssh/id_rsa
            pool: default
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
        mode: '0644'
      register: kcli_config_created
      tags: ['config']

    - name: Install kcli wrapper script to fix HOME issue
      copy:
        src: files/kcli-wrapper.sh
        dest: /usr/local/bin/kcli
        owner: root
        group: root
        mode: '0755'
      register: kcli_wrapper_installed
      tags: ['config']

    - name: Check if runner is already configured
      stat:
        path: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}/.runner"
      register: runner_configured
      loop: "{{ configurations }}"
      tags: ['config']

    - name: Configure GitHub runner
      become_user: "{{ runner_user }}"
      command: >
        ./config.sh --unattended --replace
        --name {{ item.item.name }}-{{ uid }}
        --url {{ item.item.url }}
        --token {{ runner_tokens[item.item.key_name] }}
        --labels {{ item.item.tag }}
        --work data
      args:
        chdir: "{{ runner_base_dir }}/{{ item.item.name }}-{{ uid }}"
      loop: "{{ runner_configured.results }}"
      when: not item.stat.exists
      no_log: true  # Don't log tokens
      register: runner_config_result
      failed_when: 
        - runner_config_result.rc != 0
        - "'is already configured' not in runner_config_result.stderr"
      tags: ['config']

    - name: Install runner service
      command: ./svc.sh install {{ runner_user }}
      args:
        chdir: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}"
      loop: "{{ configurations }}"
      register: service_install_result
      failed_when:
        - service_install_result.rc != 0
        - "'Failed: error: exists' not in service_install_result.stderr"
      tags: ['service']

    - name: Patch runsvc.sh to source .env file for child processes
      blockinfile:
        path: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}/runsvc.sh"
        marker: "# {mark} ANSIBLE MANAGED - SOURCE ENV"
        insertafter: "^#!/bin/bash"
        block: |
          # Source .env to make variables available to GitHub Actions workflows
          if [ -f "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}/.env" ]; then
              source "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}/.env"
          fi
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
      loop: "{{ configurations }}"
      register: runsvc_env_patched
      tags: ['service']

    - name: Get systemd service names
      shell: basename $(ls /etc/systemd/system/actions.runner.*{{ item.name }}-{{ uid }}.service 2>/dev/null | head -n1) || echo ""
      loop: "{{ configurations }}"
      register: service_names
      changed_when: false
      tags: ['service']

    - name: Create systemd override directory for each runner service
      file:
        path: "/etc/systemd/system/{{ item.stdout }}.d"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop: "{{ service_names.results }}"
      when: item.stdout != ""
      tags: ['service']

    - name: Create systemd override with environment configuration
      copy:
        dest: "/etc/systemd/system/{{ item.stdout }}.d/override.conf"
        content: |
          [Service]
          Environment="PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
          Environment="HOME=/home/{{ runner_user }}"
          EnvironmentFile={{ runner_base_dir }}/{{ item.item.name }}-{{ uid }}/.env
        owner: root
        group: root
        mode: '0644'
      loop: "{{ service_names.results }}"
      when: item.stdout != ""
      register: service_override_created
      tags: ['service']

    - name: Reload systemd daemon after creating override files
      systemd:
        daemon_reload: yes
      when: service_override_created is changed
      tags: ['service']

    - name: Restart runner services to apply EnvironmentFile changes
      systemd:
        name: "{{ item.stdout }}"
        state: restarted
      loop: "{{ service_names.results }}"
      when: 
        - item.stdout != ""
        - (service_override_created is changed or env_file_updated is changed or runsvc_env_patched is changed)
      tags: ['service']

    - name: Wait for runner services to initialize after restart
      pause:
        seconds: 5
      when: service_override_created is changed or env_file_updated is changed or runsvc_env_patched is changed
      tags: ['service']

    - name: Ensure runner services are started
      command: ./svc.sh start
      args:
        chdir: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}"
      loop: "{{ configurations }}"
      register: service_start_result
      failed_when: false  # Service might already be running
      tags: ['service']

    - name: Verify runner services are running
      command: ./svc.sh status
      args:
        chdir: "{{ runner_base_dir }}/{{ item.name }}-{{ uid }}"
      loop: "{{ configurations }}"
      register: service_status
      changed_when: false
      tags: ['verify']

    - name: Cleanup temporary files
      file:
        path: "/tmp/{{ runner_archive }}"
        state: absent
      tags: ['cleanup']

  post_tasks:
    - name: Display runner status summary
      debug:
        msg: "Runner {{ item.item.name }}-{{ uid }} status: {{ 'Running' if 'active (running)' in item.stdout else 'Not Running' }}"
      loop: "{{ service_status.results }}"
      when: service_status is defined
      tags: ['verify']
