---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-cnf
  name: 02-worker-ib-core-exclusive
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,b3B0aW9ucyBpYl9jb3JlIG5ldG5zX21vZGU9MAo=
          mode: 420
          overwrite: true
          path: /lib/modprobe.d/ib_core.conf
