---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
       "name": "ib-network-1",
       "namespace": "seba"
      }
    ]'
  labels:
    app: infiniband-client
  name: infiniband-client
  namespace: seba
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - |
          dnf install -y perftest infiniband-diags rdma-core libibverbs-utils
          sleep INF
      image: quay.io/cloud-bulldozer/k8s-netperf:latest
      imagePullPolicy: Always
      name: netperf
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
          openshift.io/ib_nic_1: "1"  # Request IB VF from ib_nic_1 resource pool
        requests:
          cpu: "2"
          memory: 1Gi
          openshift.io/ib_nic_1: "1"
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - NET_RAW
            - NET_ADMIN
  terminationGracePeriodSeconds: 2
